name: Package Creation

on: [push, pull_request]

jobs:
  pack:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Pack app as tgz
      run: tar -zcf neo4j-splunk.tgz neo4s
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: neo4j-splunk
        path: neo4j-splunk.tgz
